name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main
      - dev

jobs:
  deploy_dev:
    name: Deploy to Firebase Dev
    if: github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy to Firebase Hosting (Dev Preview Channel)
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_ICOSE_SPA }}'
          channelId: dev
          projectId: icose-spa

  deploy_prod:
    name: Deploy to Firebase Production
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy to Firebase Hosting (Production Live Channel)
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_ICOSE_SPA }}'
          channelId: live
          projectId: icose-spa
